id = "my-lumin-theme"
name = "My Lumin"
version = "0.0.2"
schema_version = 1

authors = ["Daksh Sharma <dakshsharma.tech>", "Alvydas Vitkauskas <alvydas.vitkauskas@inbox.eu>"]


description = "Modified Peppermint flavored theme; offspring of Vesper & Cursor."
repository = "https://github.com/avitkauskas/Lumin"
